// export { default as BnbCoinIcon } from './binance-coin-bnb-logo.png'
// export { default as BtcCoinIcon } from './bitcoin-btc-logo.png'
export { default as BscLogo } from './bsc-logo.png'
export { default as HeroPatternBg } from './hero-pattern-bg.svg'
export { default as ArrowIcon } from './IconArrow.svg'
export { default as DescendIcon } from './iconDescend.svg'
export { default as DropdownIcon } from './iconDropdown.svg'
export { default as FilterIcon } from './iconFilter.svg'
export { default as VaultImg } from './Vault.png'
export { default as Button } from './Vault.png'
export { default as MetamaskImg } from './metamask.png'
export { default as UserDropdownIcon } from './userDropdown.svg'
export { default as MainBTCLogo } from './main-bitcoin-logo.png'
export { default as GreenBox } from './StatusGreen.png'
export { default as RedBox } from './StatusRed.png'
export { default as GreyBox } from './StatusGrey.png'
export { default as QuestionDropdown } from './questionIcon.svg'
export { default as PersonDropdown } from './personDropdown.svg'

// coin icon
export { default as BtcCoinIcon } from './btcIcon.png'
export { default as EthCoinIcon } from './ethIcon.png'
export { default as BnbCoinIcon } from './bnbIcon.png'
export { default as CakeCoinIcon } from './cakeIcon.png'
export { default as BusdBtcCoinIcon } from './busdIcon.png'
export { default as CoinDropdownArrow } from './coinDropdown.svg'

export { default as SwitchIcon } from './switch.svg'

// account detail box
export { default as CopyIcon } from './copy_icon.svg'
export { default as ShareIcon } from './share_icon.svg'
export { default as HistoryIcon } from './history_icon.svg'
export { default as DisconnectedIcon } from './disconnect_icon.svg'
export { default as SwitchHorizontal } from './switch_horizontal.svg'
